language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "auBGgo49teP7u4zOsyZACJeBlQFRt/9u2QhERtU6SCs96Kb1XNGUlhQVbcB/dEXnYEJyD2c6Ud5YhATQVmFBKvYQ+xYzf/xAaWNbc6jUYmlnstvlMtJo4DpzSSeoDjQdt8ALRKfHOjqZypSsu7C88YXHjmtYemD3iGrkAV06J5PK8/IYsaT2kBm/t05jYN6ruPAVhbr7y6z8g+hH0yVFUnNqHdHiHBXmDWHJ3V6czhBujlg6McfcaLycdT1nknzc+W+Car/LenK5igXopBMByzNlugvbpY+hbScy+faeWppKFpxCwuv9D/QmEVPbJXTBZCT/Q4YkzNDmn+RUra+CNuKvok5Lbnf1oA0HvJwnkXkdj/XVHbqtmjg0QZFpOS72pk8LKzOVJdKSiKRQe5tvrb6UCPxAh2rim4tMLslxQ/nvkP7NrM9TETGEnDbYxsxPh4ICZ98Gqf3L5Tm3Rs4xo7xBWdIwhCIBmJiQyxy/sBkb5g+ZLkn445Psxj2vMMYFAZWor4erD2jB6yDBiJoaeF9UIUcTgdCMKbMrxDRwJa0YvuCl4Wxqbk5yDDLkkmgvFR9pENK07B0fFZBOzovI+dp4EjIvt/niLTLdqNy1iW0xD6eenpS4rzsazuqE5q5BtrXQtj8jFzfbPw99PlywItSMS/DQyzb3qtdqFUhW/w8="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr ./vendor/bin/unit-tests
    - sonar-scanner
