language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "OazkhaE6Aj+YsqIUFkH3uyZAKcVCkbtBXt8oHbRIcAfQyhxNiHOgziIYJqm6GDVArUsE4B/EjpGIatEPK0FkqsJ7BzF5mBprnSQFlB6GyqWslL2NEs3RKE4j9y8zjjOtQh759v0FvsetSLgf1WDtCGDSlIu6K0zgifeXE5NYw+4wapYJGcWYGKGtlN9o6oriYo1CfQ9R0QFrp+qwHLocvJSRBwCuuRUIKNSHkb05odH/OZBlynwKHtj/RE89Ys2BnVY0mVDPVR/CjeomzRxXqgqxOWa3WchzDOan8eq+71kgRpU74LAvXaQ2ZvUozQYCJVuMesheh3GgNZFWzp7EYhbrbSvpXVQSOBUvC793bYG0oDYj1TNGvac/xvj54ABzRzwM2RmBvwXHTkaTHmY45aQyoxijzisHokC9DmKBX3fpSUeKUcUNl5KSPqbLiB5G9hzFAtHrUtPDr7Ay5Wyc8O/2tK43ThKONwlCwUlNs0+RPtjU8u5N+FGe6LuPdtB+wIE8gtjYKnGkyqVtJHseTJPZfrcXweWscV9RRJ7k7a3/wUD1NDQgdYgMqEVTXtTH3cYCY3mdokPveW+jPWjQnv/4EZlBDvuP3TgxPsTBtQ4cA3wS59fIryAxHFpburQFbI31ghfrusZrwjq71ct1OYVSDotnQTyVZ5Vcs7REPIc="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr ./vendor/bin/unit-tests
    - sonar-scanner
